spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


server:
  port: 7099
  servlet:
    context-path: /demo

elasticseach:
  host: demo

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  config: classpath:config/logback.xml

resttemplate:
  connectTimeout: 300000
  readTimeout: 300000


---
spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

server:
  port: 8011
  servlet:
    context-path: /demo

elasticseach:
  host: demo

---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

server:
  port: 8012
  servlet:
    context-path: /demo

elasticseach:
  host: demo
