spring:
  profiles:
    active: @profiles.active@

server:
  port: 7099
  servlet:
    context-path: /pindan-prod

elasticseach:
  host: pindan-prod

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ******

server:
  port: 8011
  servlet:
    context-path: /pindan-dev

elasticseach:
  host: pindan-dev

---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

server:
  port: 8012
  servlet:
    context-path: /pindan-prod

elasticseach:
  host: pindan-prod
